package com.csk.wheatherapp.utilities

object Constants {
    const val SHOW_LAT_LONG_INTENT = "SHOW_LAT_LONG_INTENT"
    const val INITIAL_LATITUDE_INTENT = "INITIAL_LATITUDE_INTENT"
    const val INITIAL_LONGITUDE_INTENT = "INITIAL_LONGITUDE_INTENT"
    const val INITIAL_ZOOM_INTENT = "INITIAL_ZOOM_INTENT"
    const val ADDRESS_REQUIRED_INTENT = "ADDRESS_REQUIRED_INTENT"
    const val HIDE_MARKER_SHADOW_INTENT = "HIDE_MARKER_SHADOW_INTENT"
    const val MARKER_DRAWABLE_RES_INTENT = "MARKER_DRAWABLE_RES_INTENT"
    const val MARKER_COLOR_RES_INTENT = "MARKER_COLOR_RES_INTENT"
    const val FAB_COLOR_RES_INTENT = "FAB_COLOR_RES_INTENT"
    const val PRIMARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
    const val SECONDARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
    const val GOOGLE_MAP_API_KEY = "GOOGLE_MAP_API_KEY"
    const val PLACE_PICKER_REQUEST = 100
    const val ADDRESS_INTENT = "ADDRESS_INTENT"
    const val AUTOCOMPLETE_PLACE_PICKER_REQUEST = 112
    const val MY_PERMISSIONS_REQUEST_LOCATION = 2564
}